apiVersion: v1
kind: Secret
metadata:
  name: odoo-db-secret
  namespace: default  
type: Opaque
stringData:
  dbname: odoo
  host: postgres-rw
  port: "5432"
  user: odoo
  username: odoo
  password: ============================
  uri: postgresql://odoo:==========================================@postgres-rw.default:5432/odoo
  jdbc-uri: jdbc:postgresql://postgres-rw.default:5432/odoo?password===============================================================h&user=odoo
  pgpass: postgres-rw:5432:odoo:odoo:===============================================
